services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@tais84671514"
      POSTGRES_DB: apiDentregaDeMercadorias

